#全局项目整体配置
spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
        # 命名空间
        namespace: ${spring.cloud.nacos.config.namespace}
        # 心跳超时(ms)
        heart-beat-timeout: 30000
        # 心跳间隔(ms)
        heart-beat-interval: 5000